language: cpp

matrix:
  include:
    # Tests build
    - os: linux
      dist: xenial
      sudo: require
      addons:
        apt:
          packages:
            - doxygen
      env:
        - DESC="Test examples and deploy documentation"
        - ARDUINO_VERSION=1.8.7

before_install:
  - wget https://downloads.arduino.cc/arduino-${ARDUINO_VERSION}-linux64.tar.xz
  - tar xf arduino-${ARDUINO_VERSION}-linux64.tar.xz
  - sudo mv arduino-${ARDUINO_VERSION} /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

script:
  - mkdir -p $HOME/Arduino/libraries
  - cp -r . $HOME/Arduino/libraries
  - cd examples
  - make deps
  - make
  - cd ..
  - ./doc/update-gh-pages.sh
