// C++ implementation of the Blue Robotics 'Ping' binary message protocol

//~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!
// THIS IS AN AUTOGENERATED FILE
// DO NOT EDIT
//~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!

#pragma once

#ifdef QT_CORE_LIB
#include <QObject>
#endif

#include "ping_message.h"

/// ping_ping360 objects provide a wrapper over vector
/// for convenient access and packing of field data
///
/// These files are generated by the ping_generator.py
/// script found in this directory

namespace PingPing360Namespace {
#ifdef QT_CORE_LIB
    Q_NAMESPACE
#endif
    enum ping_ping360_id {
        Parameters = 2302,
        DeviceId = 2300,
        FirmwareVersion = 2301,
        StationaryUploadData = 2303,
        MotorPosition = 2304,
        ForwardsUploadData = 2305,
        ReverseUploadData = 2306,
        GotoBootloader = 2600,
        Reset = 2601,
        StepForward = 2602,
        StepReverse = 2603,
        ResetPosition = 2604,
        MotorOff = 2605,
    };
#ifdef QT_CORE_LIB
    Q_ENUM_NS(ping_ping360_id)
#endif
};

class ping_ping360_parameters : public ping_message
{
public:
    ping_ping360_parameters(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_parameters(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_parameters()
        : ping_message { static_cast<uint16_t>(22) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 12; // payload size
        (uint16_t&)msgData[4] = 2302; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint8_t mode() const { uint8_t d; memcpy(&d, (payload_data(0)), 1.0); return d; };
    void set_mode(const uint8_t mode) { memcpy((payload_data(0)), &mode, 1.0);};
    uint8_t gain_setting() const { uint8_t d; memcpy(&d, (payload_data(1.0)), 1.0); return d; };
    void set_gain_setting(const uint8_t gain_setting) { memcpy((payload_data(1.0)), &gain_setting, 1.0);};
    uint16_t angle() const { uint16_t d; memcpy(&d, (payload_data(2.0)), 2.0); return d; };
    void set_angle(const uint16_t angle) { memcpy((payload_data(2.0)), &angle, 2.0);};
    uint16_t transmit_duration() const { uint16_t d; memcpy(&d, (payload_data(4.0)), 2.0); return d; };
    void set_transmit_duration(const uint16_t transmit_duration) { memcpy((payload_data(4.0)), &transmit_duration, 2.0);};
    uint16_t interval() const { uint16_t d; memcpy(&d, (payload_data(6.0)), 2.0); return d; };
    void set_interval(const uint16_t interval) { memcpy((payload_data(6.0)), &interval, 2.0);};
    uint16_t transmit_frequency() const { uint16_t d; memcpy(&d, (payload_data(8.0)), 2.0); return d; };
    void set_transmit_frequency(const uint16_t transmit_frequency) { memcpy((payload_data(8.0)), &transmit_frequency, 2.0);};
    uint16_t number_of_samples() const { uint16_t d; memcpy(&d, (payload_data(10.0)), 2.0); return d; };
    void set_number_of_samples(const uint16_t number_of_samples) { memcpy((payload_data(10.0)), &number_of_samples, 2.0);};
};

class ping_ping360_device_id : public ping_message
{
public:
    ping_ping360_device_id(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_device_id(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_device_id()
        : ping_message { static_cast<uint16_t>(11) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 1; // payload size
        (uint16_t&)msgData[4] = 2300; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint8_t device_id() const { uint8_t d; memcpy(&d, (payload_data(0)), 1.0); return d; };
    void set_device_id(const uint8_t device_id) { memcpy((payload_data(0)), &device_id, 1.0);};
};

class ping_ping360_firmware_version : public ping_message
{
public:
    ping_ping360_firmware_version(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_firmware_version(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_firmware_version()
        : ping_message { static_cast<uint16_t>(16) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 6; // payload size
        (uint16_t&)msgData[4] = 2301; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint8_t device_type() const { uint8_t d; memcpy(&d, (payload_data(0)), 1.0); return d; };
    void set_device_type(const uint8_t device_type) { memcpy((payload_data(0)), &device_type, 1.0);};
    uint8_t device_model() const { uint8_t d; memcpy(&d, (payload_data(1.0)), 1.0); return d; };
    void set_device_model(const uint8_t device_model) { memcpy((payload_data(1.0)), &device_model, 1.0);};
    uint16_t firmware_version_major() const { uint16_t d; memcpy(&d, (payload_data(2.0)), 2.0); return d; };
    void set_firmware_version_major(const uint16_t firmware_version_major) { memcpy((payload_data(2.0)), &firmware_version_major, 2.0);};
    uint16_t firmware_version_minor() const { uint16_t d; memcpy(&d, (payload_data(4.0)), 2.0); return d; };
    void set_firmware_version_minor(const uint16_t firmware_version_minor) { memcpy((payload_data(4.0)), &firmware_version_minor, 2.0);};
};

class ping_ping360_stationary_upload_data : public ping_message
{
public:
    ping_ping360_stationary_upload_data(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_stationary_upload_data(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_stationary_upload_data(uint16_t data_length
)
        : ping_message { static_cast<uint16_t>(22 + data_length) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 12 + data_length; // payload size
        (uint16_t&)msgData[4] = 2303; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint8_t mode() const { uint8_t d; memcpy(&d, (payload_data(0)), 1.0); return d; };
    void set_mode(const uint8_t mode) { memcpy((payload_data(0)), &mode, 1.0);};
    uint8_t gain_setting() const { uint8_t d; memcpy(&d, (payload_data(1.0)), 1.0); return d; };
    void set_gain_setting(const uint8_t gain_setting) { memcpy((payload_data(1.0)), &gain_setting, 1.0);};
    uint16_t angle() const { uint16_t d; memcpy(&d, (payload_data(2.0)), 2.0); return d; };
    void set_angle(const uint16_t angle) { memcpy((payload_data(2.0)), &angle, 2.0);};
    uint16_t transmit_duration() const { uint16_t d; memcpy(&d, (payload_data(4.0)), 2.0); return d; };
    void set_transmit_duration(const uint16_t transmit_duration) { memcpy((payload_data(4.0)), &transmit_duration, 2.0);};
    uint16_t interval() const { uint16_t d; memcpy(&d, (payload_data(6.0)), 2.0); return d; };
    void set_interval(const uint16_t interval) { memcpy((payload_data(6.0)), &interval, 2.0);};
    uint16_t transmit_frequency() const { uint16_t d; memcpy(&d, (payload_data(8.0)), 2.0); return d; };
    void set_transmit_frequency(const uint16_t transmit_frequency) { memcpy((payload_data(8.0)), &transmit_frequency, 2.0);};
    uint16_t data_length() const { uint16_t d; memcpy(&d, (payload_data(10.0)), 2.0); return d; };
    //TODO do this in constructor (const)
    void set_data_length(const uint16_t data_length) { memcpy((payload_data(10.0)), &data_length, 2.0);};
    uint8_t* data() const { return (uint8_t*)(payload_data(12.0)); }
    void set_data_at(const uint16_t i, const uint8_t data) { memcpy((payload_data(12.0 + i)), &data, 1); }
};

class ping_ping360_motor_position : public ping_message
{
public:
    ping_ping360_motor_position(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_motor_position(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_motor_position()
        : ping_message { static_cast<uint16_t>(12) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 2; // payload size
        (uint16_t&)msgData[4] = 2304; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint16_t angle() const { uint16_t d; memcpy(&d, (payload_data(0)), 2.0); return d; };
    void set_angle(const uint16_t angle) { memcpy((payload_data(0)), &angle, 2.0);};
};

class ping_ping360_forwards_upload_data : public ping_message
{
public:
    ping_ping360_forwards_upload_data(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_forwards_upload_data(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_forwards_upload_data(uint16_t data_length
)
        : ping_message { static_cast<uint16_t>(22 + data_length) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 12 + data_length; // payload size
        (uint16_t&)msgData[4] = 2305; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint8_t mode() const { uint8_t d; memcpy(&d, (payload_data(0)), 1.0); return d; };
    void set_mode(const uint8_t mode) { memcpy((payload_data(0)), &mode, 1.0);};
    uint8_t gain_setting() const { uint8_t d; memcpy(&d, (payload_data(1.0)), 1.0); return d; };
    void set_gain_setting(const uint8_t gain_setting) { memcpy((payload_data(1.0)), &gain_setting, 1.0);};
    uint16_t angle() const { uint16_t d; memcpy(&d, (payload_data(2.0)), 2.0); return d; };
    void set_angle(const uint16_t angle) { memcpy((payload_data(2.0)), &angle, 2.0);};
    uint16_t transmit_duration() const { uint16_t d; memcpy(&d, (payload_data(4.0)), 2.0); return d; };
    void set_transmit_duration(const uint16_t transmit_duration) { memcpy((payload_data(4.0)), &transmit_duration, 2.0);};
    uint16_t interval() const { uint16_t d; memcpy(&d, (payload_data(6.0)), 2.0); return d; };
    void set_interval(const uint16_t interval) { memcpy((payload_data(6.0)), &interval, 2.0);};
    uint16_t transmit_frequency() const { uint16_t d; memcpy(&d, (payload_data(8.0)), 2.0); return d; };
    void set_transmit_frequency(const uint16_t transmit_frequency) { memcpy((payload_data(8.0)), &transmit_frequency, 2.0);};
    uint16_t data_length() const { uint16_t d; memcpy(&d, (payload_data(10.0)), 2.0); return d; };
    //TODO do this in constructor (const)
    void set_data_length(const uint16_t data_length) { memcpy((payload_data(10.0)), &data_length, 2.0);};
    uint8_t* data() const { return (uint8_t*)(payload_data(12.0)); }
    void set_data_at(const uint16_t i, const uint8_t data) { memcpy((payload_data(12.0 + i)), &data, 1); }
};

class ping_ping360_reverse_upload_data : public ping_message
{
public:
    ping_ping360_reverse_upload_data(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_reverse_upload_data(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_reverse_upload_data(uint16_t data_length
)
        : ping_message { static_cast<uint16_t>(22 + data_length) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 12 + data_length; // payload size
        (uint16_t&)msgData[4] = 2306; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

    uint8_t mode() const { uint8_t d; memcpy(&d, (payload_data(0)), 1.0); return d; };
    void set_mode(const uint8_t mode) { memcpy((payload_data(0)), &mode, 1.0);};
    uint8_t gain_setting() const { uint8_t d; memcpy(&d, (payload_data(1.0)), 1.0); return d; };
    void set_gain_setting(const uint8_t gain_setting) { memcpy((payload_data(1.0)), &gain_setting, 1.0);};
    uint16_t angle() const { uint16_t d; memcpy(&d, (payload_data(2.0)), 2.0); return d; };
    void set_angle(const uint16_t angle) { memcpy((payload_data(2.0)), &angle, 2.0);};
    uint16_t transmit_duration() const { uint16_t d; memcpy(&d, (payload_data(4.0)), 2.0); return d; };
    void set_transmit_duration(const uint16_t transmit_duration) { memcpy((payload_data(4.0)), &transmit_duration, 2.0);};
    uint16_t interval() const { uint16_t d; memcpy(&d, (payload_data(6.0)), 2.0); return d; };
    void set_interval(const uint16_t interval) { memcpy((payload_data(6.0)), &interval, 2.0);};
    uint16_t transmit_frequency() const { uint16_t d; memcpy(&d, (payload_data(8.0)), 2.0); return d; };
    void set_transmit_frequency(const uint16_t transmit_frequency) { memcpy((payload_data(8.0)), &transmit_frequency, 2.0);};
    uint16_t data_length() const { uint16_t d; memcpy(&d, (payload_data(10.0)), 2.0); return d; };
    //TODO do this in constructor (const)
    void set_data_length(const uint16_t data_length) { memcpy((payload_data(10.0)), &data_length, 2.0);};
    uint8_t* data() const { return (uint8_t*)(payload_data(12.0)); }
    void set_data_at(const uint16_t i, const uint8_t data) { memcpy((payload_data(12.0 + i)), &data, 1); }
};

class ping_ping360_goto_bootloader : public ping_message
{
public:
    ping_ping360_goto_bootloader(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_goto_bootloader(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_goto_bootloader()
        : ping_message { static_cast<uint16_t>(10) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 0; // payload size
        (uint16_t&)msgData[4] = 2600; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

};

class ping_ping360_reset : public ping_message
{
public:
    ping_ping360_reset(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_reset(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_reset()
        : ping_message { static_cast<uint16_t>(10) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 0; // payload size
        (uint16_t&)msgData[4] = 2601; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

};

class ping_ping360_step_forward : public ping_message
{
public:
    ping_ping360_step_forward(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_step_forward(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_step_forward()
        : ping_message { static_cast<uint16_t>(10) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 0; // payload size
        (uint16_t&)msgData[4] = 2602; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

};

class ping_ping360_step_reverse : public ping_message
{
public:
    ping_ping360_step_reverse(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_step_reverse(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_step_reverse()
        : ping_message { static_cast<uint16_t>(10) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 0; // payload size
        (uint16_t&)msgData[4] = 2603; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

};

class ping_ping360_reset_position : public ping_message
{
public:
    ping_ping360_reset_position(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_reset_position(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_reset_position()
        : ping_message { static_cast<uint16_t>(10) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 0; // payload size
        (uint16_t&)msgData[4] = 2604; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

};

class ping_ping360_motor_off : public ping_message
{
public:
    ping_ping360_motor_off(const ping_message& msg) : ping_message { msg } {}
    ping_ping360_motor_off(const uint8_t* buf, const uint16_t length) : ping_message { buf, length } {}
    ping_ping360_motor_off()
        : ping_message { static_cast<uint16_t>(10) }
    {
        msgData[0] = 'B';
        msgData[1] = 'R';
        (uint16_t&)msgData[2] = 0; // payload size
        (uint16_t&)msgData[4] = 2605; // ID
        msgData[6] = 0;
        msgData[7] = 0;
    }

};

