/*
* ping1d.h
* A device API for the Blue Robotics Ping1D echosounder
*
*~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!
* THIS IS AN AUTOGENERATED FILE
* DO NOT EDIT
*~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!~!
*
*/

#pragma once

#include "Arduino.h"
#include "Stream.h"
#include "pingmessage.h"
#include "pingmessage_all.h"
#include "ping_parser.h"

class Ping1D
{
public:
  Ping1D(Stream& ser, uint32_t baudrate);
  ~Ping1D() = default;
  
  PingMessage* read();
  size_t write(uint8_t* data, uint16_t length);

  bool initialize(uint16_t ping_interval_ms = 50, uint32_t speed_of_sound = 1500000);

  PingMessage* waitReply(enum Ping1DNamespace::msg_ping1D_id id, uint16_t timeout_ms);

  
  void handleMessage(PingMessage* pmsg);

  // ex ping_msg_ping1D_voltage_5 msg(*pd.request(Ping1DNamespace::Voltage_5));
  PingMessage* request(enum Ping1DNamespace::msg_ping1D_id id, uint16_t timeout_ms = 400);
  
  // ex auto msg = pd.request<ping_msg_ping1D_voltage_5>();
  template <typename T>
  T* request();

  bool update() {
      return request(Ping1DNamespace::Distance_simple);
  }

    /** Device information
    *   Returns a dictionary of the reply payload
    *   @return device_type: Device type. 0: 1D Echosounder
    *   @return device_model: Device model. 0: Ping1D
    *   @return fw_version_major: Firmware version major number.
    *   @return fw_version_minor: Firmware version minor number.
    */
    bool get_fw_version(uint8_t* device_type = nullptr,
                      uint8_t* device_model = nullptr,
                      uint16_t* fw_version_major = nullptr,
                      uint16_t* fw_version_minor = nullptr);

    /** The device ID.
    *   Returns a dictionary of the reply payload
    *   @return device_id: The device ID (0-254). 255 is reserved for broadcast messages.
    */
    bool get_device_id(uint8_t* device_id = nullptr);

    /** The 5V rail voltage.
    *   Returns a dictionary of the reply payload
    *   @return mvolts: Units: mV; The 5V rail voltage.
    */
    bool get_voltage_5(uint16_t* mvolts = nullptr);

    /** The speed of sound used for distance calculations.
    *   Returns a dictionary of the reply payload
    *   @return speed_of_sound: Units: mm/s; The speed of sound in the measurement medium. ~1,500,000 mm/s for water.
    */
    bool get_speed_of_sound(uint32_t* speed_of_sound = nullptr);

    /** The scan range for acoustic measurements. Measurements returned by the device will lie in the range (scan_start, scan_start + scan_length).
    *   Returns a dictionary of the reply payload
    *   @return scan_start: Units: mm; The beginning of the scan range in mm from the transducer.
    *   @return scan_length: Units: mm; The length of the scan range.
    */
    bool get_range(uint32_t* scan_start = nullptr,
                      uint32_t* scan_length = nullptr);

    /** The current operating mode of the device. Manual mode allows for manual selection of the gain and scan range.
    *   Returns a dictionary of the reply payload
    *   @return mode_auto: 0: manual mode, 1: auto mode
    */
    bool get_mode_auto(uint8_t* mode_auto = nullptr);

    /** The interval between acoustic measurements.
    *   Returns a dictionary of the reply payload
    *   @return ping_rate: Units: ms; The interval between acoustic measurements.
    */
    bool get_ping_rate(uint16_t* ping_rate = nullptr);

    /** The current gain setting.
    *   Returns a dictionary of the reply payload
    *   @return gain_index: 0: 0.6dB, 1: 1.8dB, 2: 5.5dB, 3: 12.9dB, 4: 30.2dB, 5: 66.1dB, 6: 144dB
    */
    bool get_gain_index(uint32_t* gain_index = nullptr);

    /** The duration of the acoustic activation/transmission.
    *   Returns a dictionary of the reply payload
    *   @return pulse_usec: Units: microseconds; Acoustic pulse duration.
    */
    bool get_pulse_usec(uint16_t* pulse_usec = nullptr);

    /** General information.
    *   Returns a dictionary of the reply payload
    *   @return fw_version_major: Firmware major version.
    *   @return fw_version_minor: Firmware minor version.
    *   @return mvolts: Units: mV; Device supply voltage.
    *   @return ping_rate: Units: ms; The interval between acoustic measurements.
    *   @return gain_index: The current gain setting. 0: 0.6dB, 1: 1.8dB, 2: 5.5dB, 3: 12.9dB, 4: 30.2dB, 5: 66.1dB, 6: 144dB
    *   @return mode_auto: The current operating mode of the device. 0: manual mode, 1: auto mode
    */
    bool get_general_info(uint16_t* fw_version_major = nullptr,
                      uint16_t* fw_version_minor = nullptr,
                      uint16_t* mvolts = nullptr,
                      uint16_t* ping_rate = nullptr,
                      uint8_t* gain_index = nullptr,
                      uint8_t* mode_auto = nullptr);

    /** The distance to target with confidence estimate.
    *   Returns a dictionary of the reply payload
    *   @return distance: Units: mm; Distance to the target.
    *   @return confidence: Units: %; Confidence in the distance measurement.
    */
    bool get_distance_simple(uint32_t* distance = nullptr,
                      uint8_t* confidence = nullptr);

    /** 
    *   Returns a dictionary of the reply payload
    *   @return distance: Units: mm; The current return distance determined for the most recent acoustic measurement.
    *   @return confidence: Units: %; Confidence in the most recent range measurement.
    *   @return pulse_usec: Units: us; The acoustic pulse length during acoustic transmission/activation.
    *   @return ping_number: The pulse/measurement count since boot.
    *   @return scan_start: Units: mm; The beginning of the scan region in mm from the transducer.
    *   @return scan_length: Units: mm; The length of the scan region.
    *   @return gain_index: The current gain setting. 0: 0.6dB, 1: 1.8dB, 2: 5.5dB, 3: 12.9dB, 4: 30.2dB, 5: 66.1dB, 6: 144dB
    */
    bool get_distance(uint32_t* distance = nullptr,
                      uint16_t* confidence = nullptr,
                      uint16_t* pulse_usec = nullptr,
                      uint32_t* ping_number = nullptr,
                      uint32_t* scan_start = nullptr,
                      uint32_t* scan_length = nullptr,
                      uint32_t* gain_index = nullptr);

    /** Temperature of the device cpu.
    *   Returns a dictionary of the reply payload
    *   @return temp: Units: cC; The temperature in centi-degrees Centigrade (100 * degrees C).
    */
    bool get_processor_temperature(uint16_t* temp = nullptr);

    /** Temperature of the on-board thermistor.
    *   Returns a dictionary of the reply payload
    *   @return temp: Units: cC; The temperature in centi-degrees Centigrade (100 * degrees C).
    */
    bool get_pcb_temperature(uint16_t* temp = nullptr);

    /** Acoustic output enabled state.
    *   Returns a dictionary of the reply payload
    *   @return enable: The state of the acoustic output. 0: disabled, 1:enabled
    */
    bool get_ping_enable(uint8_t* enable = nullptr);

    /** A profile produced from a single acoustic measurement. The data returned is an array of response strength at even intervals across the scan region. The scan region is defined as the region between <scan_start> and <scan_start + scan_length> millimeters away from the transducer. A distance measurement to the target is also provided.
    *   Returns a dictionary of the reply payload
    *   @return distance: Units: mm; The current return distance determined for the most recent acoustic measurement.
    *   @return confidence: Units: %; Confidence in the most recent range measurement.
    *   @return pulse_usec: Units: us; The acoustic pulse length during acoustic transmission/activation.
    *   @return ping_number: The pulse/measurement count since boot.
    *   @return scan_start: Units: mm; The beginning of the scan region in mm from the transducer.
    *   @return scan_length: Units: mm; The length of the scan region.
    *   @return gain_index: The current gain setting. 0: 0.6dB, 1: 1.8dB, 2: 5.5dB, 3: 12.9dB, 4: 30.2dB, 5: 66.1dB, 6: 144dB
    *   @return num_points: The number of data points for the profile. (The length of the proceeding array)
    *   @return data: An array of return strength measurements taken at regular intervals across the scan region.
    */
    bool get_profile(uint32_t* distance = nullptr,
                      uint16_t* confidence = nullptr,
                      uint16_t* pulse_usec = nullptr,
                      uint32_t* ping_number = nullptr,
                      uint32_t* scan_start = nullptr,
                      uint32_t* scan_length = nullptr,
                      uint32_t* gain_index = nullptr,
                      uint16_t* num_points = nullptr,
                      uint8_t* data = nullptr);

    /** The protocol version
    *   Returns a dictionary of the reply payload
    *   @return protocol_version: 
    */
    bool get_protocol_version(uint32_t* protocol_version = nullptr);


    /** Set the device ID.
    *   @param device_id - Device ID (0-254). 255 is reserved for broadcast messages.
    */
    bool set_device_id(uint8_t device_id, bool verify = true);

    /** Set the scan range for acoustic measurements.
    *   @param scan_start - Units: mm; 
    *   @param scan_length - Units: mm; The length of the scan range.
    */
    bool set_range(uint32_t scan_start, uint32_t scan_length, bool verify = true);

    /** Set the speed of sound used for distance calculations.
    *   @param speed_of_sound - Units: mm/s; The speed of sound in the measurement medium. ~1,500,000 mm/s for water.
    */
    bool set_speed_of_sound(uint32_t speed_of_sound, bool verify = true);

    /** Set automatic or manual mode. Manual mode allows for manual selection of the gain and scan range.
    *   @param mode_auto - 0: manual mode. 1: auto mode.
    */
    bool set_mode_auto(uint8_t mode_auto, bool verify = true);

    /** The interval between acoustic measurements.
    *   @param ping_rate - Units: ms; The interval between acoustic measurements.
    */
    bool set_ping_rate(uint16_t ping_rate, bool verify = true);

    /** Set the current gain selection.
    *   @param gain_index - 0: 0.6dB, 1: 1.8dB, 2: 5.5dB, 3: 12.9dB, 4: 30.2dB, 5: 66.1dB, 6: 144dB
    */
    bool set_gain_index(uint8_t gain_index, bool verify = true);

    /** Enable or disable acoustic measurements.
    *   @param enable - 0: Disable, 1: Enable.
    */
    bool set_ping_enable(uint8_t enable, bool verify = true);


    /** Return the latest value received
    */
    uint16_t num_points() { return _num_points; }

    /** Return the latest value received
    */
    uint16_t mvolts() { return _mvolts; }

    /** Return the latest value received
    */
    uint16_t confidence() { return _confidence; }

    /** Return the latest value received
    */
    uint8_t enable() { return _enable; }

    /** Return the latest value received
    */
    uint8_t device_type() { return _device_type; }

    /** Return the latest value received
    */
    uint16_t temp() { return _temp; }

    /** Return the latest value received
    */
    uint32_t distance() { return _distance; }

    /** Return the latest value received
    */
    uint8_t device_model() { return _device_model; }

    /** Return the latest value received
    */
    uint32_t speed_of_sound() { return _speed_of_sound; }

    /** Return the latest value received
    */
    uint16_t fw_version_major() { return _fw_version_major; }

    /** Return the latest value received
    */
    uint32_t ping_number() { return _ping_number; }

    /** Return the latest value received
    */
    uint8_t data() { return _data; }

    /** Return the latest value received
    */
    uint8_t mode_auto() { return _mode_auto; }

    /** Return the latest value received
    */
    uint32_t scan_start() { return _scan_start; }

    /** Return the latest value received
    */
    uint16_t fw_version_minor() { return _fw_version_minor; }

    /** Return the latest value received
    */
    uint32_t protocol_version() { return _protocol_version; }

    /** Return the latest value received
    */
    uint32_t scan_length() { return _scan_length; }

    /** Return the latest value received
    */
    uint32_t gain_index() { return _gain_index; }

    /** Return the latest value received
    */
    uint16_t ping_rate() { return _ping_rate; }

    /** Return the latest value received
    */
    uint16_t pulse_usec() { return _pulse_usec; }

    /** Return the latest value received
    */
    uint8_t device_id() { return _device_id; }


private:
  Stream& _stream;
  PingParser _parser;

    // The number of data points for the profile. (The length of the proceeding array)
    uint16_t _num_points;

    // Device supply voltage.
    uint16_t _mvolts;

    // Confidence in the most recent range measurement.
    uint16_t _confidence;

    // The state of the acoustic output. 0: disabled, 1:enabled
    uint8_t _enable;

    // Device type. 0: 1D Echosounder
    uint8_t _device_type;

    // The temperature in centi-degrees Centigrade (100 * degrees C).
    uint16_t _temp;

    // The current return distance determined for the most recent acoustic measurement.
    uint32_t _distance;

    // Device model. 0: Ping1D
    uint8_t _device_model;

    // The speed of sound in the measurement medium. ~1,500,000 mm/s for water.
    uint32_t _speed_of_sound;

    // Firmware major version.
    uint16_t _fw_version_major;

    // The pulse/measurement count since boot.
    uint32_t _ping_number;

    // An array of return strength measurements taken at regular intervals across the scan region.
    uint8_t _data;

    // The current operating mode of the device. 0: manual mode, 1: auto mode
    uint8_t _mode_auto;

    // The beginning of the scan region in mm from the transducer.
    uint32_t _scan_start;

    // Firmware minor version.
    uint16_t _fw_version_minor;

    // 
    uint32_t _protocol_version;

    // The length of the scan region.
    uint32_t _scan_length;

    // The current gain setting. 0: 0.6dB, 1: 1.8dB, 2: 5.5dB, 3: 12.9dB, 4: 30.2dB, 5: 66.1dB, 6: 144dB
    uint32_t _gain_index;

    // The interval between acoustic measurements.
    uint16_t _ping_rate;

    // The acoustic pulse length during acoustic transmission/activation.
    uint16_t _pulse_usec;

    // The device ID (0-254). 255 is reserved for broadcast messages.
    uint8_t _device_id;

};
